### ISSUE TITLE
Providing headers in the form of a Headers instance results in cookies not being sent

### ISSUE THREAD

**Issue by NoahAndrews** [jkhsjdhjs/node-fetch-cookies#11]
This code sample works as expected:
```js
const options = {
	headers: {
		"User-Agent": "myUserAgent"
	}
};
fetch(cookieJar, url, options);
```

However, this sample results in the `User-Agent` header being sent in place of the `cookie` header :
```js
const options = {
	headers: new Headers({
		"User-Agent": "myUserAgent"
	})
};
fetch(cookieJar, url, options);
```

**Comment by jkhsjdhjs** [comment]
I added support for the node-fetch [`Headers`](https://github.com/node-fetch/node-fetch#class-headers) class. I can't support the `Headers` class implemented in browsers or electron, because it's not available in nodejs.

**Comment by NoahAndrews** [comment]
nice!
