### ISSUE TITLE
Redirect logic does not change method to GET

### ISSUE THREAD

**Issue by jonatanschroeder** [jkhsjdhjs/node-fetch-cookies#19]
The fix to #4 is very welcome. The problem, though, is that the method in the redirection is not changed. Note that redirections using [status codes like 301/302/303 should change the method to GET](https://www.rfc-editor.org/rfc/rfc9110.html#name-redirection-3xx) and, for the same reason, get rid of the body and length. Redirections with 307/308 can maintain the method. This is [implemented in the node-fetch functionality](https://github.com/node-fetch/node-fetch/blob/8b3320d2a7c07bce4afc6b2bf6c3bbddda85b01f/src/index.js#L222-L227).

**Comment by jkhsjdhjs** [comment]
Hey, thanks for reporting this bug! I've pushed 1bdb506614e570451375604764e9c97605deb161, which should™ fix this issue. Please let me know whether it does for you. Thanks in advance!

**Comment by jonatanschroeder** [comment]
> Hey, thanks for reporting this bug! I've pushed [1bdb506](https://github.com/jkhsjdhjs/node-fetch-cookies/commit/1bdb506614e570451375604764e9c97605deb161), which should™ fix this issue. Please let me know whether it does for you. Thanks in advance!

Unfortunately I've had to move on with a different library so I don't have an easy way to test this now, but the code looks correct. Thanks for the fix.
